# Generated by Django 3.1.4 on 2020-12-16 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researchdata', '0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_image',
            field=models.ImageField(blank=True, null=True, upload_to='researchdata-questions-images'),
        ),
    ]
